[package]
name = "linear-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
