// Generated by Flint compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include "../runtime/runtime.h"

// Type definitions
typedef struct flint_list flint_list_t;
typedef struct flint_record flint_record_t;
typedef void* flint_value_t;
typedef void (*function_ptr_t)(void);

// C Import: stdio.h as stdio (already included)

int main(void) {
    // Initialize Flint runtime
    flint_init_runtime();

    // Flint main function body
    {
        printf("Hello, World!\n");
    }

    // Cleanup runtime
    flint_cleanup_runtime();
    return 0;
}

// Runtime helper functions
void flint_runtime_error(const char* message) {
    fprintf(stderr, "Flint runtime error: %s\n", message);
    exit(1);
}

