// Generated by Flint compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include "../runtime/runtime.h"

Value* add(Value* x, Value* y) {
    Value* add_result_0 = flint_create_logical_var(true);
    // Arithmetic constraint: add_result_0 = x + y
    // Create result as logic variable
    Value* result = flint_create_logical_var(false);

    // Try to solve the constraint using the runtime
    flint_solve_arithmetic_constraint(x, y, result, "add");
    // Always return the result variable, even if constraint couldn't be solved immediately
    return result;
}

// Register add in function registry
void register_add() {
    flint_register_function_2("add", add);
}

int flint_main() {
    Value* z = flint_create_logical_var(true);
    Value* call_result_1 = flint_create_logical_var(true);
    // Function call constraint: call_result_1 = add(z, flint_create_integer(5))
    flint_unify(call_result_1, add(z, flint_create_integer(5)), flint_get_global_env());
    flint_unify(call_result_1, flint_create_integer(9), flint_get_global_env());
    printf("Result: %d\n", flint_value_to_int(z));
    return 0;
}

int main(void) {
    // Initialize Flint runtime
    flint_init_runtime();

    // Register user-defined functions
    register_add();

    // Call main function
    int result = flint_main();

    // Cleanup runtime
    flint_cleanup_runtime();
    return result;
}
